user_agent: "sri-dx-acquisition/0.1"
timeout_s: 20
per_domain_delay_s: 5
max_depth: 2
max_docs: 300
max_workers: 15
verify_ssl: false

whitelist_domains:
  - msdmanuals.com
  - mayoclinic.org
  - www.nhs.uk
  #   - www.cdc.gov

seeds:
  # - seed_id: seed_0012
  #   seed_group: msd_topics_en
  #   url: https://www.msdmanuals.com/professional/health-topics

  # - seed_id: seed_0013
  #   seed_group: nhs_conditions_az_en
  #   url: https://www.nhs.uk/conditions/

  # - seed_id: seed_0014
  #   seed_group: mayo_conditions_az_en
  #   url: https://www.mayoclinic.org/diseases-conditions

  - seed_id: seed_001
    seed_group: msd_guides_en
    url: https://www.msdmanuals.com/professional/endocrine-and-metabolic-disorders/diabetes-mellitus-and-disorders-of-carbohydrate-metabolism/diabetes-mellitus-dm

  - seed_id: seed_002
    seed_group: msd_guides_en
    url: https://www.msdmanuals.com/professional/pulmonary-disorders/asthma-and-related-disorders/asthma

  - seed_id: seed_003
    seed_group: msd_guides_en
    url: https://www.msdmanuals.com/professional/cardiovascular-disorders/heart-failure/overview-of-heart-failure

  - seed_id: seed_004
    seed_group: msd_guides_en
    url: https://www.msdmanuals.com/professional/pulmonary-disorders/pneumonia/overview-of-pneumonia

  - seed_id: seed_005
    seed_group: msd_guides_en
    url: https://www.msdmanuals.com/professional/neurologic-disorders/meningitis/overview-of-meningitis

  - seed_id: seed_006
    seed_group: nhs_conditions_en
    url: https://www.nhs.uk/conditions/asthma/

  - seed_id: seed_007
    seed_group: nhs_conditions_en
    url: https://www.nhs.uk/conditions/pneumonia/

  - seed_id: seed_008
    seed_group: nhs_conditions_en
    url: https://www.nhs.uk/conditions/multiple-sclerosis/

  - seed_id: seed_009
    seed_group: nhs_conditions_en
    url: https://www.nhs.uk/conditions/epilepsy/

#   - seed_id: seed_010
#     seed_group: cdc_symptoms_dx_tx
#     url: https://www.cdc.gov/yellow-fever/symptoms-diagnosis-treatment/index.html

#   - seed_id: seed_011
#     seed_group: cdc_symptoms_dx_tx
#     url: https://www.cdc.gov/chikungunya/symptoms-diagnosis-treatment/index.html

out:
  dir: data/processed
  html_name: docs_html.jsonl
  pdf_name: docs_pdf.jsonl

persist:
  min_words_html: 120
  min_words_pdf: 120
  max_out_links_html: 200

  skip_url_substrings:
    - "/about"
    - "/contact"
    - "/terms"
  #  - "/index"
    - "/all_"
    - "/tests-and-treatments"
    - "/symptoms"
    - "/medicines"
    - "/vaccinations"
    - "/search"

  detect_az_index: true